-- MySQL Script generated by MySQL Workbench
-- mié 11 nov 2020 09:25:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `DNI` VARCHAR(9) NOT NULL,
  `fecha_nacimiento` VARCHAR(10) NULL,
  `nivel_estudios` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `cabeza_familia` VARCHAR(45) NOT NULL,
  `vivienda` INT NULL,
  PRIMARY KEY (`DNI`),
  CONSTRAINT `cabeza_familia`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`persona` (`fecha_nacimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zona` (
  `nombre` VARCHAR(45) NOT NULL,
  `área` VARCHAR(45) NULL,
  `concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calle` (
  `nombre` VARCHAR(45) NOT NULL,
  `longitud` INT NULL,
  `tipo` VARCHAR(15) NULL,
  `cantidad_carriles` INT NULL,
  `zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `zona_idx` (`zona` ASC) VISIBLE,
  CONSTRAINT `zona`
    FOREIGN KEY (`zona`)
    REFERENCES `mydb`.`zona` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bloque` (
  `número` INT NOT NULL,
  `año_construccion` VARCHAR(10) NULL,
  `superficie` INT NULL,
  `calle` VARCHAR(45) NULL,
  PRIMARY KEY (`número`),
  INDEX `calle_idx` (`calle` ASC) VISIBLE,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`calle` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vivienda_unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vivienda_unifamiliar` (
  `número` INT NOT NULL,
  `año_construccion` VARCHAR(45) NULL,
  `superficie` INT NULL,
  `número_habitaciones` INT NULL,
  `eficiencia_energetica` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  PRIMARY KEY (`número`),
  INDEX `calle_idx` (`calle` ASC) VISIBLE,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`calle` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`piso` (
  `letra` INT NOT NULL,
  `planta` VARCHAR(45) NOT NULL,
  `superficie` INT NULL,
  `número_habitaciones` INT NULL,
  `eficiencia_energetica` VARCHAR(5) NULL,
  `bloque` INT NULL,
  PRIMARY KEY (`letra`, `planta`),
  INDEX `bloque_idx` (`bloque` ASC) VISIBLE,
  CONSTRAINT `bloque`
    FOREIGN KEY (`bloque`)
    REFERENCES `mydb`.`bloque` (`número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vívero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vívero` (
  `ubicación` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `horario de apertura` VARCHAR(45) NULL,
  `horario de cierre` VARCHAR(45) NULL,
  PRIMARY KEY (`ubicación`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `nombre` VARCHAR(45) NOT NULL,
  `Vívero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  CONSTRAINT `Vívero`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Vívero` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
