-- MySQL Script generated by MySQL Workbench
-- mié 11 nov 2020 09:24:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vívero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vívero` (
  `ubicación` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `horario_apertura` VARCHAR(45) NOT NULL,
  `horario_cierre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ubicación`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`),
  CONSTRAINT `Nombre`
    FOREIGN KEY (`Nombre`)
    REFERENCES `mydb`.`Vívero` (`ubicación`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `DNI` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `tipo de contrato` VARCHAR(45) NULL,
  `código_SS` INT NULL,
  `zona` VARCHAR(45) NULL,
  `fecha_inicio` VARCHAR(10) NULL,
  `fecha_fin` VARCHAR(10) NULL,
  PRIMARY KEY (`DNI`),
  INDEX `zona_idx` (`zona` ASC) VISIBLE,
  CONSTRAINT `zona`
    FOREIGN KEY (`zona`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `código_barras` INT NOT NULL,
  `caducidad` VARCHAR(10) NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` FLOAT NULL,
  `tipo` VARCHAR(45) NULL,
  `stock` INT NULL,
  `zona` VARCHAR(45) NULL,
  PRIMARY KEY (`código_barras`),
  INDEX `zona_idx` (`zona` ASC) VISIBLE,
  CONSTRAINT `zona`
    FOREIGN KEY (`zona`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `DNI` VARCHAR(9) NOT NULL,
  `código_fidelización` INT NULL,
  `num_tarjeta` INT NULL,
  `bonificación` FLOAT NULL,
  `gasto_mensual` FLOAT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `código` INT NOT NULL,
  `fecha` VARCHAR(10) NULL,
  `cliente` VARCHAR(10) NOT NULL,
  `producto` INT NOT NULL,
  `empleado` VARCHAR(9) NULL,
  PRIMARY KEY (`código`),
  INDEX `empleado_idx` (`empleado` ASC) VISIBLE,
  INDEX `producto_idx` (`producto` ASC) VISIBLE,
  INDEX `cliente_idx` (`cliente` ASC) VISIBLE,
  CONSTRAINT `producto`
    FOREIGN KEY (`producto`)
    REFERENCES `mydb`.`producto` (`código_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empleado`
    FOREIGN KEY (`empleado`)
    REFERENCES `mydb`.`empleado` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `mydb`.`cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
